try to fail

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -13,9 +13,7 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Check Repository Name
+        if: 1 != 2
         run: |
-          IFS='/' read -r username repository <<< ${{ github.repository }}
-          if [[ "$repository" =~ "a-project-name" ]]; then
-            echo "Repository name is not allowed, failing workflow."
-            exit 1
-          fi
+          echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
+          exit 1
