succeed with run

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -15,8 +15,7 @@ jobs:
       - name: Check Repository Name
         run: |
           IFS='/' read -r username repository <<< ${{ github.repository }}
-          if [[ "a-project-name" =~ "a-project-name" ]]; then
-          echo "Repository name is not allowed, failing workflow."
-          exit 1
-
+          if [[ "a-project-name" == *"a-project-name"* ]]; then
+            echo "Repository name is not allowed, failing workflow."
+            exit 1
   
